#!/usr/bin/env bash
# The platform tier's CI gate — the Laravel/Pest suite against real PostgreSQL and real Redis.
#
#   Usage:  infra/ci/platform-suite.sh
#
# Requires Docker and NOTHING else on the host: no PHP, no composer, no Node. Same rule as
# the rest of the repository (infra/README.md → Host-agnostic tooling), and the reason CI
# runs this script rather than a list of workflow steps — a red build has to be reproducible
# on a laptop or it cannot be investigated.
#
# PARITY is what the image choices buy. The runner is the SAME webserver image DDEV runs, so
# `php8.5` and its extension set are the dev container's rather than a lookalike's; Redis is
# the topology's pinned tag started with the platform's OWN infra/shared/redis/redis.conf, so
# a change that breaks that config fails here rather than at the next `ddev start`.
#
# NOT started: the document engine. Every test that touches it uses Http::fake(), so a live
# engine would prove nothing; it has its own gate in infra/ci/engine-suite.sh.
#
# ---------------------------------------------------------------------------------------
# WHAT MAKES THIS RED (docs/conventions/orchestration.md → "green by absence"):
#   1. Any failing or errored test.
#   2. Composer failing to install from the lock file.
#   3. Filament assets missing after install — asserted explicitly in run-suite.sh, because
#      the tree LOOKS complete without them (they are gitignored, generated by a composer
#      hook) and the symptom is a 200-but-broken UI rather than an error.
#   4. QUEUE_CONNECTION no longer being `sync` — see infra/ci/platform/queue-guard.php.
#   5. Postgres or Redis not answering their protocols within the timeout.
#
# THE SUITE RUNS ALONE, and in CI that is free: the tree is fixed at checkout and this is the
# only job touching the database. tests/Pest.php also takes a PostgreSQL advisory lock, but
# note what that lock does and does not do — it serializes suite RUNS, not EDITS. It cannot
# protect a running suite from source files changing underneath it, which is what produced
# 11 failures that vanished on re-run during the T24 audit. CI is immune to that specific
# problem by construction, which is why the constraint is "run alone" and not "the lock
# handles it".
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
readonly REPO_ROOT

# All three pinned exactly. The webserver tag tracks the DDEV version in use (ddev v1.25.3);
# the Redis tag is the same one .ddev/.env.redis pins for the topology — if one moves without
# the other, CI and development stop testing the same Redis.
readonly RUNNER_IMAGE=ddev/ddev-webserver:v1.25.3
readonly POSTGRES_IMAGE=postgres:16
readonly REDIS_IMAGE=redis:7.4.10-bookworm

readonly NETWORK=oir-flow-ci-platform-net
readonly DB_CONTAINER=oir-flow-ci-platform-db
readonly REDIS_CONTAINER=oir-flow-ci-platform-redis

# Network aliases are NOT cosmetic: phpunit.xml hard-codes DB_HOST=db, and the application
# reads REDIS_HOST. The services must answer to exactly these names.
readonly DB_ALIAS=db
readonly REDIS_ALIAS=redis

# The cluster superuser. Matches phpunit.xml's DB_USERNAME/DB_PASSWORD, and must be able to
# CREATE DATABASE (tests/Pest.php creates oirflow_test) and CREATE EXTENSION (the first
# migration installs unaccent and pg_trgm into the `extensions` schema).
readonly DB_USER=db
readonly DB_PASSWORD=db

# CI-only, not a secret. MUST decode to EXACTLY 32 bytes — AES-256-CBC validates the length at
# construction, and a short key does not fail at boot but inside the first test touching an
# encrypted cookie, as "Unsupported cipher" repeated across dozens of unrelated tests.
readonly CI_APP_KEY=base64:Y2ktb25seS1pbnNlY3VyZS1hcHAta2V5LTEyMzQ1Njc=

log() {
  echo "==> $*"
}

# One platform-gate run at a time on this machine. The names below are distinct from the DDEV
# project's but NOT from a second copy of this gate, and the up-front `cleanup` is destructive
# by design. This serializes the CONTAINERS; tests/Pest.php's advisory lock serializes the
# SUITE — a different resource, whose loss produces connection errors rather than a wait.
source "$(dirname "${BASH_SOURCE[0]}")/lock.sh"
ci_take_gate_lock platform

# The persistent composer download cache, shared with the seam gate; the rationale and the
# helper definitions live in infra/ci/composer-cache.sh.
source "$(dirname "${BASH_SOURCE[0]}")/composer-cache.sh"
ci_ensure_composer_cache

cleanup() {
  # Best-effort and silent: a failed run must still leave the machine clean, and a cleanup
  # error must never mask the failure being reported.
  docker rm -f "${DB_CONTAINER}" "${REDIS_CONTAINER}" >/dev/null 2>&1 || true
  docker network rm "${NETWORK}" >/dev/null 2>&1 || true
}
# REGISTERED AFTER THE LOCK IS HELD, and the order is load-bearing: a process still waiting on
# the lock owns no containers, so a trap installed before acquisition would — if that waiter
# were interrupted — delete the containers of the run it is waiting for. See lock.sh.
trap cleanup EXIT

# Names are distinct from the DDEV project's containers, so running this on a developer's
# machine can never touch the project they have running. Safe to run up front only because the
# lock above guarantees any run whose containers these might be has already finished.
cleanup

cd "${REPO_ROOT}"

# Fail here, in a second, rather than as dozens of unrelated red tests four minutes in.
# Learned the expensive way while building this gate: a 31-byte key produced 62 failures
# across FirstLoginTest, LoginThrottleTest, TenantLifecycleJournalTest and others, none of
# which mentioned the key in their names.
readonly CI_APP_KEY_BYTES="$(printf '%s' "${CI_APP_KEY#base64:}" | base64 -d 2>/dev/null | wc -c)"
if [[ "${CI_APP_KEY_BYTES}" != "32" ]]; then
  echo "error: CI_APP_KEY decodes to ${CI_APP_KEY_BYTES} bytes, but AES-256-CBC requires exactly 32." >&2
  echo "The suite would fail with 'Unsupported cipher or incorrect key length' in every test" >&2
  echo "that touches a session or an encrypted cookie — which reads as an application defect." >&2
  exit 1
fi

log "creating the CI network"
docker network create "${NETWORK}" >/dev/null

log "starting postgres (${POSTGRES_IMAGE}) as '${DB_ALIAS}'"
docker run --detach \
  --name "${DB_CONTAINER}" \
  --network "${NETWORK}" \
  --network-alias "${DB_ALIAS}" \
  --env "POSTGRES_USER=${DB_USER}" \
  --env "POSTGRES_PASSWORD=${DB_PASSWORD}" \
  --env "POSTGRES_DB=${DB_USER}" \
  --tmpfs /var/lib/postgresql/data:rw \
  "${POSTGRES_IMAGE}" >/dev/null

log "starting redis (${REDIS_IMAGE}) as '${REDIS_ALIAS}', using the platform's own redis.conf"
docker run --detach \
  --name "${REDIS_CONTAINER}" \
  --network "${NETWORK}" \
  --network-alias "${REDIS_ALIAS}" \
  --volume "${REPO_ROOT}/infra/shared/redis:/etc/redis/conf:ro" \
  "${REDIS_IMAGE}" \
  /etc/redis/conf/redis.conf >/dev/null

log "running the suite in ${RUNNER_IMAGE}"
# The repository goes in READ-ONLY: run-suite.sh copies it to a writable /app inside the
# container, so nothing the install produces reaches the caller's working tree.
# --entrypoint bash: this image's entrypoint expects to be orchestrated by DDEV.
readonly CI_ENGINE_KEY=ci-only-insecure-engine-key

log "composer cache: volume ${CI_COMPOSER_CACHE_VOLUME} at ${CI_COMPOSER_CACHE_DIR} (max ${CI_COMPOSER_MAX_PARALLEL_HTTP} parallel downloads)"

# Unquoted on purpose — see ci_composer_cache_docker_args: it emits fixed literals, so word
# splitting is what turns them into separate docker arguments.
# shellcheck disable=SC2046
docker run --rm \
  --network "${NETWORK}" \
  --volume "${REPO_ROOT}:/src:ro" \
  $(ci_composer_cache_docker_args) \
  --env "APP_KEY=${CI_APP_KEY}" \
  --env "ENGINE_URL=http://engine:8000" \
  --env "ENGINE_KEY=${CI_ENGINE_KEY}" \
  --env "REDIS_HOST=${REDIS_ALIAS}" \
  --env "REDIS_PORT=6379" \
  --env "COMPOSER_ALLOW_SUPERUSER=1" \
  --entrypoint bash \
  "${RUNNER_IMAGE}" \
  /src/infra/ci/platform/run-suite.sh

log "platform gate: green"
